spring.application.name=JWT-Basics1
# MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/jwtbookdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.url=jdbc:mysql://localhost:3306/jwtbookdb
#jwtbookdb
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin

#newly added
spring.jpa.hibernate.ddl-auto=update

jwt.secret = ahdsdjjsdhjsdhdks884788676565r5tft4eefdr456rdesw3w33wsdcghjjikuw2sz34832233

